export const DOWNLOAD_BULK_DATA_OBJECT = 'BULK_DATA_OBJECTS/DOWNLOAD_BULK_DATA_OBJECT';
export const DOWNLOAD_BULK_DATA_OBJECT_COMPLETE = 'BULK_DATA_OBJECTS/DOWNLOAD_BULK_DATA_OBJECT_COMPLETE';
export const DOWNLOAD_BULK_DATA_OBJECT_PROGRESS = 'BULK_DATA_OBJECTS/DOWNLOAD_BULK_DATA_OBJECT_PROGRESS';
export const DOWNLOAD_BULK_DATA_OBJECTS = 'BULK_DATA_OBJECTS/DOWNLOAD_BULK_DATA_OBJECTS';
