export const DOWNLOAD_SETS = 'SETS/DOWNLOAD_SETS';
export const HYDRATE_SETS = 'SETS/HYDRATE_SETS';
export const SET_SORT_DIRECTION = 'SETS/SET_SORT_DIRECTION';
export const SET_SORT_FIELD = 'SETS/SET_SORT_FIELD';
